apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c7qw88gc1-go 
  janus-idp.io/tekton: c7qw88gc1-go
  backstage.io/kubernetes-id: c7qw88gc1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c7qw88gc1-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml