apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c7qw88gc1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c7qw88gc1-go 
  name: c7qw88gc1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c7qw88gc1-go 
